[#165] Keycloak support added
kbss-cvut/termit pull request #173
Opened 2022-08-25 19:42 UTC by FilipKopecky

Added keycloak

2022-08-29 15:25 UTC, FilipKopecky commented
Added profiles to the relevant test classes + removed isAuthenticated from `/configuration` endpoint. The previously failed tests should be working now. @ledsoft

2022-09-02 12:39 UTC, ledsoft requested changes
I figured out the problem with `PreAuthorize` - TermIt internal roles work hierarchically, so `ROLE_FULL_USER` automatically includes `ROLE_RESTRICTED_USER`. Keycloak-based authorization does not work like this.
To fix it, create a custom authority mapper and pass it to `KeycloakAuthenticationProvider`. See the inline comment. After that, all the extra `PreAuthorize("isAuthenticated()")` can be removed and the PR will me much more compact.

2022-09-02 12:39 UTC, ledsoft commented on pom.xml
> +                    <target>11</target>
Replace with `java.version` from properties.

2022-09-02 12:39 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/config/SecurityKeycloakConfig.java
> +                new SimpleAuthorityMapper());
Replace with a custom authority mapper looking like this:
```java
public class HierarchicalRoleBasedAuthorityMapper implements GrantedAuthoritiesMapper {

    @Override
    public Collection<? extends GrantedAuthority> mapAuthorities(Collection<? extends GrantedAuthority> authorities) {
        return authorities.stream().map(a -> {
                              final UserRole role = UserRole.fromRoleName(a.getAuthority());
                              return role.getGranted();
                          }).flatMap(roles -> roles.stream().map(r -> new SimpleGrantedAuthority(r.getName())))
                          .collect(Collectors.toSet());
    }
}
```

2022-09-05 10:24 UTC, ledsoft approved these changes
LGTM

2022-09-05 10:24 UTC, merged