Method Throttling
kbss-cvut/termit pull request #295
Opened 2024-09-11 13:09 UTC by lukaskabc

This PR addresses performance issues from #287 and #285

# Identified problems
- **vocabulary validation** - was being executed on a request from the frontend. Results were cached, but the whole cache was evicted on any modification of any vocabulary. Vocabulary validation also requires synchronization as the validator is not thread-safe, blocking each thread assigned to handle the validation request until the previous validation is performed (This was probably also preventing the app from running out of memory when multiple validations would be processed concurrently). Validation is a time and resource-consuming task.
- **asynchronous term occurrence saving** - Many individual tasks might get scheduled during occurrence saving, but it's not even guaranteed when they will be saved (...when Spring has time...)
- **text analysis** - similar problem with validation, executed on term modification; it is time and resource-consuming, and it results in async term occurrence saving. Text analysis of a term was executed before text analysis of all terms from the vocabulary, resulting in duplicated processing.
- **Single code deployment** - TermIt is deployed in a single core environment, eliminating the asynchronous processing benefits.

# New features
## Throttle & Debounce
This PR introduces an option to throttle and debounce method calls.

![method throttling & debouncing](https://raw.githubusercontent.com/kbss-cvut/termit/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/doc/throttle-debounce.png)

> Do not review linked test cases before reading about return type support and throttled futures

The goal of method throttling & debouncing is to execute tasks **asynchronously** on a **fixed** thread pool merging often method calls into a **single task** execution with the **newest data** from the most recent method call [[test case](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/test/java/cz/cvut/kbss/termit/util/throttle/ThrottleAspectTest.java#L280)]. Throttling ensures that if the method task were not executed in the last [X seconds](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/main/java/cz/cvut/kbss/termit/util/Constants.java#L59), it would be scheduled for immediate execution [[test case](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/test/java/cz/cvut/kbss/termit/util/throttle/ThrottleAspectTest.java#L256)]. Otherwise, its execution will be delayed (debounced) so that it can be merged with potential future calls (it guarantees that when no future call comes, the task will be executed with the data from the last call). Task execution also ensures that when a task is time-consuming and its execution is taking longer than the actual throttle interval, a new call to the throttled method won't result in the concurrent execution of the same task [[test case](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/test/java/cz/cvut/kbss/termit/util/throttle/ThrottleAspectTest.java#L876)].
When a thread is already executing a throttled task, it will ignore any further throttling and will execute all methods synchronously [[test case](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/test/java/cz/cvut/kbss/termit/util/throttle/ThrottleAspectTest.java#L533)].

Throttling & Debouncing is realized with the [Throttle](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/main/java/cz/cvut/kbss/termit/util/throttle/Throttle.java) annotation which is handled by the [Throttle aspect](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/main/java/cz/cvut/kbss/termit/util/throttle/ThrottleAspect.java). 
> Aspect is configured using Spring AOC XML syntax to not utilize AspectJ. Once AspectJ is removed from dependencies, it should be possible to replace XML configuration with annotations. Aspect is disabled for the test profile.

Throttle annotation supports methods with **void** return type out of the box.
The whole method is, in that case, considered a task that should be throttled, and the method itself will be executed asynchronously.

There is also support for methods returning a [Future](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Future.html). However, the concrete returned object **MUST** be [ThrottledFuture](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/main/java/cz/cvut/kbss/termit/util/throttle/ThrottledFuture.java). Otherwise the aspect will throw appropriate exception on the method call (there is no way to safely check that on application start).
When a method returns future (ThrottledFuture), the method itself will be executed synchronously allowing to prepare the task that should be throttled and also to provide a cached result which may be acquired by a caller method from [CacheableFuture](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/main/java/cz/cvut/kbss/termit/util/throttle/CacheableFuture.java) interface before the actual future resolution. The actual task and cached result is then provided through the returned ThrottledFuture object.
An example can be seen in updated [result caching validator](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/main/java/cz/cvut/kbss/termit/persistence/validation/ResultCachingValidator.java#L94) where the method `validate` will be executed synchronously by the caller thread, checking the cache state and returning already resolved future when the cache is not dirty, or returning the future with the time-consuming task `runValidation` method and providing the cached result. Method `runValidation` will be executed asynchronously.

Throttled future also implements a [chainable future](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/main/java/cz/cvut/kbss/termit/util/throttle/ChainableFuture.java) interface, which allows to chain a task that will be executed once the future is resolved.
This, for example, allows the [WebSocket controller](https://github.com/lukaskabc/termit/blob/85d2e4b6b736ce91c7d4cc94230cc4c53a1aed7e/src/main/java/cz/cvut/kbss/termit/websocket/VocabularySocketController.java#L58) to respond with the cached result and set a task that will send a new result to the client once new data are available. This prevents the thread from being blocked while awaiting a future resolution.

Scheduling throttled futures also support their cancellation based on their **group**.  
This, for example, allows to cancel scheduling a task to analyze a definition of a single term while an analysis of all terms from the vocabulary is scheduled.

## Disadvantages
- a throttled method can't use the previous transaction - when the throttled method is called during a transaction, the throttled task is executed asynchronously without access to the original transaction. However, when the [Transactional](https://docs.spring.io/spring-framework/docs/6.1.12/javadoc-api/org/springframework/transaction/annotation/Transactional.html) annotation is present on the same method as the Throttled annotation, the task will be executed in transactional context.
> Unfortunately, I was not able to make a detection of active transaction context work. It might be a feature missing in Jopa (and TransactionSynchronizationManager), or I might just miss something; anyway, the explicit transactional annotation is required for the transaction to work.

## Long-running tasks
As the application will now run some time-consuming tasks in the background, it will push the status of such tasks to the clients via WebSocket, allowing to display information about the activity to the user.

Currently, it's only possible to name the throttled method by a constant. So, the user will know that there is a validation in progress but won't know whi [...]

2024-09-12 07:17 UTC, ledsoft requested changes
Haven't tried, yet so these are purely based on reviewing the code here.

A bunch of inline comments, plus these general remarks:
- Replace JetBrains annotations (particularly `NotNull`) with their Spring equivalents (`NonNull`). I stopped pointing that out after a couple of files. We don't use `Nullable`, it is assumed by default. I also don't see any reason for using these annotations on fields, use them only on public methods
- There are several files containing formatting changes only. This makes the already large PR even larger
- I also have a question regarding the necessity of using XML-configured aspect, but let's discuss that on our meeting

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/config/WebAppConfig.java
These changes seem completely superfluous and don't seem to have any real effect.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/event/VocabularyContentModifiedEvent.java
> +import org.jetbrains.annotations.NotNull;
Use Spring's `NonNull` instead of the JetBrains `NotNull`.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/event/VocabularyCreatedEvent.java
> +import org.jetbrains.annotations.NotNull;
DTTO, use Spring `NonNull`.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/event/VocabularyEvent.java
> +import org.jetbrains.annotations.NotNull;
DTTO, use Spring `NonNull`

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/event/VocabularyFileTextAnalysisFinishedEvent.java
> +public class VocabularyFileTextAnalysisFinishedEvent extends VocabularyEvent {
I would prefer to call it `FileTextAnalysisFinishedEvent`, without the `Vocabulary` part, as it is not that important.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/event/VocabularyTermDefinitionTextAnalysisFinishedEvent.java
> +public class VocabularyTermDefinitionTextAnalysisFinishedEvent extends VocabularyEvent {
Again, remove the `Vocabulary` part of the class name, `TermDefinition` is enough to communicate the meaning of the class.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/event/VocabularyValidationFinishedEvent.java
> +    @Unmodifiable
We don't use this annotation in TermIt, remove it. It is superfluous since you create an unmodifiable collection in the constructor anyway (which is by itself uncommon I would say, as typically you would prevent modification on component interfaces, not within the component itself).

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/event/VocabularyValidationFinishedEvent.java
> +    @NotNull
Remove the annotation from here, I think it is useless on a field, null check (or annotation) should be on component interface - constructor in this case.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/event/VocabularyValidationFinishedEvent.java
> +import org.jetbrains.annotations.NotNull;
Use Spring's `NonNull`.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/event/VocabularyWillBeRemovedEvent.java
> +import org.jetbrains.annotations.NotNull;
Use Spring's `NonNull`

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/persistence/dao/TermOccurrenceDao.java
> +        LOG.debug("Removed all occurrences from {}", sourceContext);
Use `Utils.uriToString` to stringify sourceContext.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/persistence/dao/VocabularyDao.java
> +     * @param vocabulary Base vocabulary, whose imports should be retrieved
Identifier of base vocabulary... Also the parameter should be called `vocabularyIri`.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/persistence/validation/ResultCachingValidator.java
> +import org.jetbrains.annotations.Nullable;
Again, don't use JetBrains annotations, use Spring `NonNull`. We don't use `Nullable`, it is assumed by default.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/persistence/validation/ResultCachingValidator.java
> +    private final Map<URI, @NotNull Collection<URI>> vocabularyClosure = new ConcurrentHashMap<>();
Again, we don't use `NotNull` (or rather `NonNull`) annotations on fields, just on component interface (setters, constructors).

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/persistence/validation/ResultCachingValidator.java
> +    public void evictVocabularyCache(VocabularyEvent event) {
Name is misleading, the method does not evict anything.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/rest/ResourceController.java
All changes except for two lines (one OpenAPI doc and the other log message removal) are just formatting changes

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/rest/TermController.java
Again, only useless formatting changes that make the PR bigger for no reason.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/rest/VocabularyController.java
More useless formatting changes. I propose to remove the warning logs, leave these controller as they are and later discuss what to do with the explicit analysis endpoints. We can either remove them altogether, or move the to administration controller.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/rest/handler/RestExceptionHandler.java
> +        // prevents from logging exceptions caused be broken connection with a client
"Prevents exceptions caused by broken connection with client from logging"

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/security/JwtUtils.java
Useless formatting changes.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/service/document/SynchronousTermOccurrenceSaver.java
Since there is no longer an asynchronous term occurrence saver, we can probably rename this one to just `TermOccurrenceSaver`.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/service/document/SynchronousTermOccurrenceSaver.java
Yeah, and merge it with the `TermOccurrenceSaver` inteface.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/service/document/html/HtmlSelectorGenerators.java
> +        return generators.parallelStream().map(g -> g.generateSelector(elements)).collect(Collectors.toSet());
It is generally discouraged to use parallelStream in web application environments because they by default use the same threadpool. Also, do you have evidence that using a parallelStream in this particular case leads to a noticeable speedup? If not, please revert the change.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/service/document/html/TextPositionSelectorGenerator.java
> +        AtomicInteger counter = new AtomicInteger();
Why are you using an `AtomicInteger`? I don't see any way multiple threads could access the counter, so I feel the change brings nothing.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/service/document/html/TextPositionSelectorGenerator.java
> +        AtomicInteger counter = new AtomicInteger();
Also, if this (and the rest of the changes in this file) is related to the parallelStream usage in HtmlSelectorGenerators, see my comment there.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/util/Constants.java
> +    public static final Duration THROTTLE_DISCARD_THRESHOLD = Duration.ofMinutes(1);
These should be configurable, too.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/util/Pair.java
> +    public static class Comparable<T extends java.lang.Comparable<T>, V extends java.lang.Comparable<V>>
`ComparablePair` perhaps?

2024-09-12 07:17 UTC, ledsoft commented on src/test/java/cz/cvut/kbss/termit/service/document/AnnotationGeneratorTest.java
Useless formatting changes.

2024-09-12 07:17 UTC, ledsoft commented on src/test/java/cz/cvut/kbss/termit/rest/ResourceControllerTest.java
Again, I see only formatting changes.

2024-09-12 07:17 UTC, ledsoft commented on src/main/java/cz/cvut/kbss/termit/model/Vocabulary.java
> +        final StringBuilder builder = new StringBuilder();
Don't use `StringBuilder` unless constructing some complex string (or in a loop), the JVM is able to optimize string concatenation as necessary.

2024-09-12 10:23 UTC, lukaskabc commented on src/main/java/cz/cvut/kbss/termit/rest/ResourceController.java
keeping without change as discussed on our meeting

2024-09-12 10:23 UTC, lukaskabc commented on src/main/java/cz/cvut/kbss/termit/config/WebAppConfig.java
keeping without change as discussed on our meeting

2024-09-12 10:25 UTC, lukaskabc commented on src/main/java/cz/cvut/kbss/termit/rest/TermController.java
keeping without change as discussed on our meeting

2024-09-12 11:04 UTC, lukaskabc commented on src/main/java/cz/cvut/kbss/termit/security/JwtUtils.java
keeping without change as discussed on our meeting

2024-09-12 12:24 UTC, lukaskabc commented on src/test/java/cz/cvut/kbss/termit/service/document/AnnotationGeneratorTest.java
keeping without change as discussed on our meeting

2024-09-12 12:24 UTC, lukaskabc commented on src/test/java/cz/cvut/kbss/termit/rest/ResourceControllerTest.java
keeping without change as discussed on our meeting

2024-09-12 14:31 UTC, lukaskabc commented on src/main/java/cz/cvut/kbss/termit/service/document/html/TextPositionSelectorGenerator.java
> +        AtomicInteger counter = new AtomicInteger();
The atomic reference was required for access from the lambda function. However, I reviewed the changes and reverted them as they didn't have the desired effect. It was an attempt to eliminate the construction of a whole string to retrieve its length.

2024-09-13 08:25 UTC, ledsoft approved these changes
LGTM, works nicely. I added a small fix for situations where terms are related to each other, as it was throwing exception due to the analysis of the whole vocabulary running in the same transaction.

2024-09-13 08:25 UTC, merged